package com.zblouse.fantasyfitness.core;

public enum EventType {
    CREATE_ACCOUNT_RESPONSE, USER_EXIST_EVENT, WORKOUT_UPDATE_EVENT, DEVICE_LOCATION_EVENT,
    LOCATION_FETCH_EVENT,USER_GAME_STATE_UPDATE_EVENT, WORKOUT_COMPLETE_EVENT,
    USER_GAME_STATE_FETCH_RESPONSE_EVENT, WORKOUT_START_EVENT, WORKOUT_RECORD_READ_EVENT, EXPLORE_ACTION_EVENT,
    DIALOG_SELECTED_EVENT, DECK_FETCH_EVENT
}
