package com.zblouse.fantasyfitness.core;

public enum EventType {
    CREATE_ACCOUNT_RESPONSE, USER_EXIST_EVENT, TIME_UPDATE_EVENT, DEVICE_LOCATION_EVENT,
    WORKOUT_DISTANCE_UPDATE_EVENT, LOCATION_FETCH_EVENT,USER_GAME_STATE_UPDATE_EVENT, WORKOUT_COMPLETE_EVENT,
    USER_GAME_STATE_FETCH_RESPONSE_EVENT
}
